application: top
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets
- url: /images
  static_dir: static/images
- url: /javascripts
  static_dir: static/javascripts
- url: /.*
  script: main.py

